# Generated by Django 5.0.2 on 2025-05-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_group', models.CharField(choices=[('dg', 'DG Maintenance'), ('ac', 'AC Maintenance'), ('site_visit', 'Site Visit')], max_length=20, unique=True)),
                ('schema', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
