# Generated by Django 5.0.2 on 2025-09-26 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Unknown Company', max_length=255)),
                ('employee_id', models.CharField(default='EMP-0000', max_length=50, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='employee/passports/')),
                ('signature_photo', models.ImageField(blank=True, null=True, upload_to='employee/signatures/')),
                ('mobile_number', models.CharField(default='0000000000', max_length=10)),
                ('user_type', models.CharField(choices=[('AREML', 'AREML'), ('SWEAR', 'SWEAR'), ('3rd Party', '3rd Party'), ('Customer', 'Customer')], default='AREML', max_length=50)),
                ('user_role', models.CharField(choices=[('DG SME', 'DG SME'), ('AC SME', 'AC SME'), ('Circle Head', 'Circle Head'), ('IME Lead', 'IME Lead'), ('Surveillance Lead', 'Surveillance Lead'), ('Infra Lead', 'Infra Lead'), ('Energy Lead', 'Energy Lead'), ('HSSE Lead', 'HSSE Lead'), ('Energy MIS', 'Energy MIS'), ('Infra MIS', 'Infra MIS'), ('Operational Lead', 'Operational Lead'), ('Cluster Lead', 'Cluster Lead'), ('Supervisor', 'Supervisor'), ('Technician', 'Technician')], default='Technician', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
