# Generated by Django 5.0.2 on 2025-09-26 16:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Unknown Company', max_length=255)),
                ('employee_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='admin/passports/')),
                ('signature_photo', models.ImageField(blank=True, null=True, upload_to='admin/signatures/')),
                ('mobile_number', models.CharField(default='0000000000', max_length=10)),
                ('user_type', models.CharField(choices=[('AREML', 'AREML'), ('SWEAR', 'SWEAR'), ('3rd Party', '3rd Party'), ('Customer', 'Customer')], default='AREML', max_length=50)),
                ('user_role', models.CharField(choices=[('DG SME', 'DG SME'), ('AC SME', 'AC SME'), ('circle Head', 'circle Head'), ('IME Lead', 'IME Lead'), ('Surveillance Lead', 'Surveillance Lead'), ('Infra Lead', 'Infra Lead'), ('Energy Lead', 'Energy Lead'), ('HSSE Lead', 'HSSE Lead'), ('Energy MIS', 'Energy MIS'), ('Infra MIS', 'Infra MIS'), ('Operational Lead', 'Operational Lead'), ('Cluster Lead', 'Cluster Lead'), ('Supervisor', 'Supervisor'), ('Technician', 'Technician')], default='Technician', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGN_TASK', 'Assign Task'), ('UPDATE_TASK', 'Update Task'), ('DELETE_TASK', 'Delete Task'), ('REVIEW_REPORT', 'Review Report'), ('APPROVE_REPORT', 'Approve Report'), ('REJECT_REPORT', 'Reject Report'), ('CREATE_EMPLOYEE', 'Create Employee'), ('DELETE_EMPLOYEE', 'Delete Employee'), ('TOGGLE_EMPLOYEE', 'Toggle Employee Status')], max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('global_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('wait_for_review', 'Wait for Review'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('planned_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cluster_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color_code', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
