# Generated by Django 5.2.1 on 2025-09-04 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
