# Generated by Django 5.0.2 on 2025-09-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('cluster_name', models.CharField(max_length=100)),
                ('site_name', models.CharField(max_length=100)),
                ('latitude', models.CharField(blank=True, max_length=30, null=True)),
                ('longitude', models.CharField(blank=True, max_length=30, null=True)),
                ('circle', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
        ),
    ]
