# Generated by Django 5.2.1 on 2025-09-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_reset_otp_user_reset_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='passport_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='signature_photo',
            field=models.ImageField(blank=True, null=True, upload_to='signature_photos/'),
        ),
    ]
